<?php
return [
    // Branding & Navigation
    'brand_name' => 'SIRTECH',
    'home' => 'Nyumbani',
    'services' => 'Huduma',
    'features' => 'Vipengele',
    'benefits' => 'Faida',
    'contact' => 'Mawasiliano',
    'sign_up_now' => 'Jisajili Sasa',
    'english' => 'Kiingereza',
    'swahili' => 'Kiswahili',

    // Hero Section
    'welcome_heading' => 'Kuza Mitandao Yako ya Kijamii na SIRTECH SMM',
    'welcome_subheading' => 'Paneli bora ya SMM kwa watu mashuhuri, biashara na mashirika. Huduma za masoko ya mitandao ya kijamii haraka, za kuaminika na nafuu.',
    'learn_more' => 'Jifunze Zaidi',
    'hero_image_alt' => 'Takwimu za Mitandao ya Kijamii',

    // Stats Section
    'happy_clients' => 'Wateja Wenye Furaha',
    'support' => 'Msaada',
    'uptime' => 'Uhakika',

    // Features Section
    'explore_services' => 'Gundua Huduma Zetu',
    'discover_services' => 'Gundua suluhisho bora za SMM kwa mahitaji yako.',
    'instant_delivery' => 'Uwasilishaji wa Haraka',
    'instant_delivery_desc' => 'Pata oda zako mara moja kupitia mfumo wetu wa kiotomatiki.',
    'high_quality' => 'Ubora wa Juu',
    'high_quality_desc' => 'Tunatoa huduma bora pekee kwa matokeo halisi.',
    'support_desc' => 'Msaada wa wateja masaa 24/7 kukusaidia wakati wowote.',
    'view_services' => 'Tazama Huduma',

    // How It Works
    'how_it_works' => 'Jinsi Inavyofanya Kazi',
    'how_it_works_image_alt' => 'Jinsi inavyofanya kazi',
    'step1' => 'Jisajili kwa akaunti bila malipo',
    'step2' => 'Ongeza fedha kwenye salio lako',
    'step3' => 'Chagua huduma na weka oda yako',
    'step4' => 'Fatilia hali ya oda yako papo hapo',
    'step5' => 'Furahia ukuaji wa mitandao yako ya kijamii!',
    'get_started' => 'Anza Sasa',

    // Benefits Section
    'why_choose' => 'Kwa Nini Uchague SIRTECH SMM?',
    'real_results' => 'Tunatoa matokeo halisi kwa ukuaji wa mitandao yako ya kijamii',
    'high_speed_delivery' => 'Uwasilishaji wa Kasi',
    'high_speed_delivery_desc' => 'Pata oda zako zikikamilishwa haraka kuliko washindani kupitia mfumo wetu ulioboreshwa.',
    'secure_private' => 'Salama & Faragha',
    'secure_private_desc' => 'Usalama wa akaunti yako ni kipaumbele chetu kwa API salama na ulinzi wa faragha.',
    'real_analytics' => 'Takwimu Halisi',
    'real_analytics_desc' => 'Fatilia ukuaji wako kwa takwimu na vipimo vya utendaji.',
    'unlimited_resources' => 'Rasilimali Zisizo na Kikomo',
    'unlimited_resources_desc' => 'Kuza uwepo wako wa mitandao ya kijamii bila mipaka.',
    'competitive_pricing' => 'Bei Nafuu',
    'competitive_pricing_desc' => 'Huduma bora kwa bei zinazoshinda ushindani.',
    'dedicated_support' => 'Msaada wa Kujitolea',
    'dedicated_support_desc' => 'Timu yetu ya wataalamu inapatikana 24/7 kukusaidia kwa maswali yoyote.',

    // CTA Section
    'cta_heading' => 'Tayari Kutawala Mitandao ya Kijamii?',
    'cta_subheading' => 'Jiunge na maelfu ya wauzaji na mashirika yanayokua na SIRTECH SMM',
    'get_started_now' => 'Anza Sasa',

    // Footer
    'footer_desc' => 'Huduma bora za masoko ya mitandao ya kijamii kwa watu mashuhuri, biashara na mashirika.',
    'quick_links' => 'Viungo Muhimu',
    'instagram_growth' => 'Ukuaji wa Instagram',
    'youtube_views' => 'Mionekano ya YouTube',
    'twitter_engagement' => 'Ushirikiano wa Twitter',
    'tiktok_followers' => 'Wafuasi wa TikTok',
    'facebook_likes' => 'Likes za Ukurasa wa Facebook',
    'contact_us' => 'Wasiliana Nasi',
    'address' => 'Digital Plaza, Tech City',
    'phone' => '+255 123 456 789',
    'email' => 'msaada@sirtechsmm.com',
    'all_rights_reserved' => 'Haki Zote Zimehifadhiwa.',

    // Services Page Additions
    'available_services' => 'Huduma Zinazopatikana',
    'services_subtitle' => 'Tazama na uagize kutoka kwenye huduma zetu mbalimbali za SMM hapa chini.',
    'search_services_placeholder' => 'Tafuta huduma...',
    'no_services_available' => 'Hakuna huduma zinazopatikana kwa sasa.',
    'back_to_home' => 'Rudi Nyumbani',

    // Admin Panel
    'admin_dashboard' => 'Dashibodi ya Admin',
    'dashboard' => 'Dashibodi',
    'users' => 'Watumiaji',
    'orders' => 'Oda',
    'activity' => 'Shughuli',
    'revenue' => 'Mapato',
    'services' => 'Huduma',
    'logout' => 'Toka',
    'total_users' => 'Jumla ya Watumiaji',
    'total_orders' => 'Jumla ya Oda',
    'active_users' => 'Watumiaji Hai',
    'view_balances_in' => 'Angalia Salio Katika:',
    'mother_panel_balance' => 'Salio la Paneli Kuu',
    'income' => 'Mapato (Amana za Watumiaji)',
    'expenditure' => 'Matumizi (Oda)',

    // Admin Panel - Services Management
    'local_services' => 'Huduma za Ndani',
    'import_services' => 'Ingiza Huduma',
    'edit_service' => 'Hariri Huduma',
    'service_name' => 'Jina la Huduma',
    'service_description' => 'Maelezo ya Huduma',
    'service_price_usd' => 'Bei (USD)',
    'service_price_tzs' => 'Bei (TZS)',
    'service_visibility' => 'Mwonekano',
    'show' => 'Onyesha',
    'hide' => 'Ficha',
    'bulk_show' => 'Onyesha Zote',
    'bulk_hide' => 'Ficha Zote',
    'convert_currency' => 'Badilisha Sarafu',
    'update_service' => 'Sasisha Huduma',
    'delete_service' => 'Futa Huduma',
    'no_services_found' => 'Hakuna huduma zilizopatikana.',
    'user_activity' => 'Shughuli za Mtumiaji',
    'last_10_orders' => 'Oda 10 za Mwisho',
    'order_management' => 'Usimamizi wa Oda',
    'total_revenue' => 'Jumla ya Mapato',
    'service_management' => 'Usimamizi wa Huduma',
    'import_new_service_from_api' => 'Ingiza Huduma Mpya Kutoka API',
    'service_management' => 'Usimamizi wa Huduma',
    'bulk_service_visibility' => 'Mwonekano wa Huduma kwa Wingi',
    'select_action' => 'Chagua ',
    'show_all' => 'Onyesha Zote',
    'hide_all' => 'Ficha Zote',
    'user_management' => 'Usimamizi wa Watumiaji',
    'balance_overview' => 'Muonekano wa Salio',
    'view_prices_in' => 'Tazama Bei Katika',
    'place_order' => 'Weka Oda',
    'search_placeholder' => 'Tafuta huduma...',
    'select_service' => 'chagua huduma',
    'quantity' => 'Kiasi',
    'quantity_hint' => 'Ingiza kiasi unachotaka kuagiza',
    'link_hint' => 'https://example.com',
    'transaction_history' => 'Historia ya Muamala',
    'user_email' => 'Barua pepe',
    'admin_support_tickets' => 'Tiketi za Msaada wa Admin',
    'welcome_title' => 'karibu sirtech smm'

];

